### ISSUE TITLE
ground truth file

### ISSUE THREAD

**Issue by ssscj** [darelab2014/Dinopore#2]
Hi, thanks for developing Dinopore. I want the train the Dinopore model from scratch. And I found the groundtruth_class_regression.tsv and the groundtruth_class_regression_all.tsv in codeocean.  And these two ground truth file only contain 3 columns, id, ref, rate, not the 5 columns mentioned in the README. Example file in misc on github is correct. Could you provide the whole ground truth file? Thanks!

**Comment by acarmas1** [comment]
hey were you able to find the right .tsv file?
I'm confused on how I'm supposed to generate this file

**Comment by skchronicles** [comment]
@hengjwj @darelab2014 @tramanh183 
Is there an update to this issue?

I am also interested in using this tool with my own data; however, it is not clear what I should be provided to the `-c option` of the **mainscript1.sh** and **mainscript1.sh**. Just for reference, I am working with human data.

Please let me know what you think.

**Comment by hengjwj** [comment]
Hi all, I've removed the requirement for -c in mainscript1.sh as the subscripts do not require the file (mainscript1 and mainscript2 were originally together). As mentioned in #3, the file is used to assess model accuracy/precision based on ground truth from Illumina sequencing data. Kindly refer to #3 for the example files on formatting. Thanks!
