### ISSUE TITLE
Raw data not available on SRA

### ISSUE THREAD

**Issue by ChaseWLW** [darelab2014/Dinopore#5]
Dear authors,

I was hoping to re-basecall and analyse the read data in Dinopore. However, the SRP record SRP363295 as provided in the paper has many empty entries, e.g. the mouse and frog ones. 

Could you please take a look into this? Thanks for the great work!

**Comment by hengjwj** [comment]
Hi @ChaseWLW , sorry for the late reply and thanks for trying out our method. I've checked some of these that show 0 spots and 0 bases. The files are actually available in "original format" (shown below).

gBlock
![image](https://user-images.githubusercontent.com/58542021/231042174-6dd4428b-cf79-45c6-a601-ab3a6a9c8a28.png)
![image](https://user-images.githubusercontent.com/58542021/231042044-58e41aaf-6c3c-45cc-8212-49cfc48a7ea0.png)

Mouse Brain
![image](https://user-images.githubusercontent.com/58542021/231042464-4c65912d-9b9d-421c-ad97-2ae58e54646f.png)
![image](https://user-images.githubusercontent.com/58542021/231042551-8d2a17ed-55c1-474c-9921-99edf0b83d68.png)

**Comment by MamgKhushi** [comment]
Hello, 
Thank you very much for your paper and the tool. 
I would like to use your Dataset for mouse with some of mine to try dinopore but I do not have access to guppy, so I can not use the fast5 files directly. Is there anyway I can get the basecalled fastq files for mouse samples to use the tools? 
It would be really helpful for me if possible, so please let me know. 

Thank you very much in advance.
