### ISSUE TITLE
How can I create my own groundtruth file

### ISSUE THREAD

**Issue by acarmas1** [darelab2014/Dinopore#6]
Hello,

I've been trying to use dinopore from a while. I want to identify A-to-I RNA editing sites from my direct RNA reads.  

In the Script #5 one of the parameters is the classref file, which is the groundtruth_class_regression.tsv. However, is this file only meant to be used for the test data set? or should I used it also when running my own data?

If not, how can I generate my own groundtruth_class_regression.tsv file?

**Comment by itslittman** [comment]
I am also wondering this.

**Comment by acarmas1** [comment]
Hello,
https://github.com/weir12/DeepEdit I found this alternative to profile A-to-I sites in direct RNA reads. Hopefully, it will help you too.
